## 
# These are the three services needed to create a website with the frontednd of WordPress
# This is a work in progress
#

services:
  image: mariadb:<add the version>
  container_name: mariadb
  restart: always
  command: "--default-authentication-plugin=mariadb_native_password"
  environment: 
    MY_ROOT_PASSWORD: password
    MYSQL_DATABASE: wpdb
    MYSQL_USER: user
    MYSQL_PASSWORD: password

worpress:
  image: wordpress:latest
  cointainer_name: wordpress
  restart: always
  volumes: 
    -./wp-content:/var/www/html/wp-content
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_NAME: wpdb
    WORDPRESS_DB_USER: user
    WORDPRESS_DB_PASSWORD: password
  ports:
    -8080:80
    -443:443

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  ports:
    - #you would add a port here if you want to
  environment:
    PMA_HOST: db
    MARIADB_ROOT_PASSWORD: password